In [1]:
import numpy as np

In [8]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
def sigmoid_derivative(x):
    return x * (1 - x)
def binary_cross_entropy(y_true, y_pred):
    return -np.mean(y_true * np.log(y_pred + 1e-7) + (1 - y_true) * np.log(1 - y_pred + 1e-7))

In [12]:
def train_neural_network(X, y, epochs=10000, lr=0.1):
    input_dim= X.shape[1]
    weights = np.random.uniform(size=(input_dim, 1)) 
    bias = np.random.uniform(size=(1,))
    for epoch in range(epochs):
        linear_output = np.dot(X, weights) + bias
        predictions = sigmoid(linear_output)
        loss = binary_cross_entropy(y, predictions)
        error = predictions - y
        d_pred = error*sigmoid_derivative(predictions)
        weights = lr*np.dot(X.T, d_pred)
        bias -= lr*np.sum(d_pred)
        if epoch % 1000 == 0:
            print(f"Epoch {epoch}, Loss: {loss:.4f}")
    return weights, bias

In [14]:
def predict(X, weights, bias):
    return sigmoid(np.dot (X, weights) + bias) >= 0.5

In [15]:
X = np.array([[0,0], [0,1], [1,0], [1,1]])
logic_gates = {
    "AND": np.array([[0], [0], [0], [1]]), 
    "OR": np.array([[0], [1], [1], [1]]), 
    "NAND": np.array([[1], [1], [1], [0]]), 
    "NOR": np.array([[1], [0], [0], [0]]), 
    "XOR": np.array([[0], [1], [1], [0]])
}
for gate_name, y in logic_gates.items():
    print(f"\nTraining for {gate_name} gate:")
    weights, bias = train_neural_network(X, y, epochs=10000, lr=0.1) 
    predictions = predict (X, weights, bias).astype(int)
    print(f"Predictions for {gate_name} gate:\n{predictions.reshape(-1)}")


Training for AND gate:
Epoch 0, Loss: 1.0218
Epoch 1000, Loss: 0.5647
Epoch 2000, Loss: 0.5647
Epoch 3000, Loss: 0.5647
Epoch 4000, Loss: 0.5647
Epoch 5000, Loss: 0.5647
Epoch 6000, Loss: 0.5647
Epoch 7000, Loss: 0.5647
Epoch 8000, Loss: 0.5647
Epoch 9000, Loss: 0.5647
Predictions for AND gate:
[0 0 0 0]

Training for OR gate:
Epoch 0, Loss: 0.5186
Epoch 1000, Loss: 0.5647
Epoch 2000, Loss: 0.5647
Epoch 3000, Loss: 0.5647
Epoch 4000, Loss: 0.5647
Epoch 5000, Loss: 0.5647
Epoch 6000, Loss: 0.5647
Epoch 7000, Loss: 0.5647
Epoch 8000, Loss: 0.5647
Epoch 9000, Loss: 0.5647
Predictions for OR gate:
[1 1 1 1]

Training for NAND gate:
Epoch 0, Loss: 0.7816
Epoch 1000, Loss: 0.5647
Epoch 2000, Loss: 0.5647
Epoch 3000, Loss: 0.5647
Epoch 4000, Loss: 0.5647
Epoch 5000, Loss: 0.5647
Epoch 6000, Loss: 0.5647
Epoch 7000, Loss: 0.5647
Epoch 8000, Loss: 0.5647
Epoch 9000, Loss: 0.5647
Predictions for NAND gate:
[1 1 1 1]

Training for NOR gate:
Epoch 0, Loss: 0.9834
Epoch 1000, Loss: 0.5647
Epoch 20